zuul_tutorial_config:
  - compose_file: docker-compose.yaml
    nodepool_file: nodepool-quickstart.yaml
  - compose_file: docker-compose.yaml
    nodepool_file: nodepool-nodes.yaml

zuul_tutorial_docker_compose_dest_base_dir: "{{ zuul.projects['opendev.org/zuul/zuul'].src_dir if not local else '../..' }}/doc/source/examples"
